import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ToastOptions, Toaster } from 'react-hot-toast';
import './globals.css';

const toastOptions: ToastOptions = {
  duration: 5000,
};

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Toaster position='top-center' toastOptions={toastOptions} />
        {children}
      </body>
    </html>
  );
}
